language: php

php:
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit -v --coverage-text
